services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///tasks.db  # Chemin de la base de données SQLite
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
